[2025-03-17T01:33:42.323+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T01:33:42.354+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_minio_dag.create_bucket_task manual__2025-03-17T01:33:39.661059+00:00 [queued]>
[2025-03-17T01:33:42.365+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_minio_dag.create_bucket_task manual__2025-03-17T01:33:39.661059+00:00 [queued]>
[2025-03-17T01:33:42.366+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-17T01:33:42.385+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_bucket_task> on 2025-03-17 01:33:39.661059+00:00
[2025-03-17T01:33:42.392+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_minio_dag', 'create_bucket_task', 'manual__2025-03-17T01:33:39.661059+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmpwfr3qkmj']
[2025-03-17T01:33:42.395+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask create_bucket_task
[2025-03-17T01:33:42.396+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=301) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-17T01:33:42.397+0000] {standard_task_runner.py:72} INFO - Started process 302 to run task
[2025-03-17T01:33:42.460+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_minio_dag.create_bucket_task manual__2025-03-17T01:33:39.661059+00:00 [running]> on host 643acaa02cac
[2025-03-17T01:33:42.569+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_minio_dag' AIRFLOW_CTX_TASK_ID='create_bucket_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T01:33:39.661059+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-17T01:33:39.661059+00:00'
[2025-03-17T01:33:42.571+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-17T01:33:42.719+0000] {logging_mixin.py:190} INFO - Error al crear el bucket: An error occurred (InvalidBucketName) when calling the CreateBucket operation: The specified bucket is not valid.
[2025-03-17T01:33:42.720+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-17T01:33:42.735+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-17T01:33:42.736+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_minio_dag, task_id=create_bucket_task, run_id=manual__2025-03-17T01:33:39.661059+00:00, execution_date=20250317T013339, start_date=20250317T013342, end_date=20250317T013342
[2025-03-17T01:33:42.814+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-17T01:33:42.846+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-17T01:33:42.849+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
